// This file will be auto-generated by Supabase CLI
// Run: npm run supabase:generate-types

export interface Database {
  public: {
    Tables: {
      stuff_categories: {
        Row: {
          id: number;
          user_id: string;
          rank: number | null;
          name: string;
          icon: string;
          property_limited_number: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          user_id: string;
          rank?: number | null;
          name: string;
          icon: string;
          property_limited_number?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string;
          rank?: number | null;
          name?: string;
          icon?: string;
          property_limited_number?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      stuff_properties: {
        Row: {
          id: number;
          user_id: string;
          category_id: number;
          name: string;
          thumbnail: string | null;
          score: number | null;
          price: number | null;
          address: string | null;
          purchase_date: string | null;
          purchase_place: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          user_id: string;
          category_id: number;
          name: string;
          thumbnail?: string | null;
          score?: number | null;
          price?: number | null;
          address?: string | null;
          purchase_date?: string | null;
          purchase_place?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string;
          category_id?: number;
          name?: string;
          thumbnail?: string | null;
          score?: number | null;
          price?: number | null;
          address?: string | null;
          purchase_date?: string | null;
          purchase_place?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      stuff_property_memos: {
        Row: {
          id: number;
          property_id: number;
          five_w: string[];
          image: string | null;
          memo: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          property_id: number;
          five_w?: string[];
          image?: string | null;
          memo?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          property_id?: number;
          five_w?: string[];
          image?: string | null;
          memo?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      stuff_wants: {
        Row: {
          id: number;
          user_id: string;
          category_id: number;
          name: string;
          thumbnail: string | null;
          score: number | null;
          price: number | null;
          brand: string | null;
          url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          user_id: string;
          category_id: number;
          name: string;
          thumbnail?: string | null;
          score?: number | null;
          price?: number | null;
          brand?: string | null;
          url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          user_id?: string;
          category_id?: number;
          name?: string;
          thumbnail?: string | null;
          score?: number | null;
          price?: number | null;
          brand?: string | null;
          url?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      stuff_want_conditions: {
        Row: {
          id: number;
          want_id: number;
          asset_threshold: number;
          period: string | null;
          max_property_count: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: number;
          want_id: number;
          asset_threshold: number;
          period?: string | null;
          max_property_count?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: number;
          want_id?: number;
          asset_threshold?: number;
          period?: string | null;
          max_property_count?: number | null;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
  };
}
